// <auto-generated />
using System;
using AgenticSoftwareEngineering.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgenticSoftwareEngineering.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Orchestration.AgentExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowNodeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orchestration_AgentExecutions", (string)null);
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Orchestration.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApproverRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Decision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PlanRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Risk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orchestration_Approvals", (string)null);
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Orchestration.ArtifactDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DependentArtifactId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId", "DependentArtifactId")
                        .IsUnique();

                    b.ToTable("Orchestration_ArtifactDependencies", (string)null);
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Orchestration.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orchestration_Decisions", (string)null);
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Orchestration.Dependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PredecessorNodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SuccessorNodeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PredecessorNodeId", "SuccessorNodeId")
                        .IsUnique();

                    b.ToTable("Orchestration_Dependencies", (string)null);
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Orchestration.EngineeringArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentReference")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProducerExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProducerNodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesArtifactId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "ArtifactType", "Version")
                        .IsUnique();

                    b.ToTable("Orchestration_EngineeringArtifacts", (string)null);
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Orchestration.PlanRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SupersedesRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "Revision")
                        .IsUnique();

                    b.ToTable("Orchestration_PlanRevisions", (string)null);
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Orchestration.PolicyEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Allowed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("EvaluatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orchestration_PolicyEvaluations", (string)null);
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Orchestration.ValidationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ValidatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orchestration_ValidationResults", (string)null);
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Orchestration.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orchestration_Workflows", (string)null);
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Orchestration.WorkflowEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("Orchestration_WorkflowEvents", (string)null);
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Orchestration.WorkflowNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("Orchestration_WorkflowNodes", (string)null);
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Urls.ClickEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ShortLinkId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShortLinkId");

                    b.ToTable("UrlShortener_ClickEvents", (string)null);
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Urls.ShortLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("UrlShortener_ShortLinks", (string)null);
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Orchestration.PlanRevision", b =>
                {
                    b.HasOne("AgenticSoftwareEngineering.Api.Domain.Orchestration.Workflow", null)
                        .WithMany("PlanRevisions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Orchestration.WorkflowEvent", b =>
                {
                    b.HasOne("AgenticSoftwareEngineering.Api.Domain.Orchestration.Workflow", null)
                        .WithMany("Events")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Orchestration.WorkflowNode", b =>
                {
                    b.HasOne("AgenticSoftwareEngineering.Api.Domain.Orchestration.Workflow", "Workflow")
                        .WithMany("Nodes")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Urls.ClickEvent", b =>
                {
                    b.HasOne("AgenticSoftwareEngineering.Api.Domain.Urls.ShortLink", "ShortLink")
                        .WithMany("Clicks")
                        .HasForeignKey("ShortLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShortLink");
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Orchestration.Workflow", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Nodes");

                    b.Navigation("PlanRevisions");
                });

            modelBuilder.Entity("AgenticSoftwareEngineering.Api.Domain.Urls.ShortLink", b =>
                {
                    b.Navigation("Clicks");
                });
#pragma warning restore 612, 618
        }
    }
}
